# Generated by Django 4.0.2 on 2022-04-22 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(default='no_image.jpg', upload_to='products/%Y/%m/%d'),
        ),
    ]
